### ISSUE TITLE
Link Front-end repo

### ISSUE THREAD

**Issue by henriquesosa** [thebergamo/ecommerce.js#13]
Just to remember. We have to link the front-end repo with this, using git submodules.

**Comment by thebergamo** [comment]
ok!

Finishing the catalog entity I will link =D

**Comment by thebergamo** [comment]
@henriquesosa I need you create some bootstrap scripts for adding frontend as a submodule, because we need start the frontend.

create a folder called scripts at root of project and create scripts there. see here for inspiration: https://github.com/thebergamo/ecommerce.js/blob/master/scripts/bootstrap

**Comment by thebergamo** [comment]
done!
